### ISSUE TITLE
Projectors colours scheme issue

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#45]
Hi Matthew,
                I tried to change the values in vesta_elements.ini to use the different colours of each projectors in projected band structure instead of defualt colours.  Because some elements colours very similar like Ga and Se elements. 
But, after changing the values didnt find any change in the colours of projected band structure orbitals. Do I need to change in any other place?

**Comment by ml-evs** [comment]
Hi Sajid, apologies for not replying in the other issue, it completely slipped my mind.

Editing the `vesta_elements.ini` is the correct way of doing this, and this way "works for me" at the moment. Are you editing the correct columns? The vesta elements file contains 8 columns per species, and the last 3 are the RGB values for the colours that vesta uses. One possible issue is that your config file does not point to the correct vesta_elements.ini file. Do you have the option set? You can be sure by taking a copy of the elements file and adding it as an absolute path in your config, as below.

Here is the default matador config, you may want to take some of these values and add them to your config too:

```yaml
  mongo:
      host: localhost
      port: 27017
      db: crystals
      default_collection: repo
      default_collection_file_path: ~/matador-db

  plotting:
      default_style: matador
      element_colours: ./vesta_elements.ini

  run3:
      castep_executable: castep
      optados_executable: optados
      scratch_prefix: .
```

**Comment by sajidurehman** [comment]
Thank you for prompt reply.  Its OK no problem. I tried it but got the issue as mentioned above.

Glad to hear i am on right track. Yes, I know last three columns represent the RGB colours. Also, have same setting in config.py as you mentioned above. But still getting same colour after changing RGB values.

Like i changed the Nitrigen RGB values 
7  N  0.74  1.55  1.460    0.76100    0.56100    0.56100 
to
7  N  0.74  1.55  1.460    1.00000    1.00000    1.00000
 
But for both RGB values getting the same color.

**Comment by sajidurehman** [comment]
I tried to use the following RGB values 
https://prtkm.github.io/files/new_elements.ini
I copied the new RGB values in vesta_elements.ini but again getting same colours.

**Comment by ml-evs** [comment]
Hmmm, that's exactly the same as what I'm doing. Could you post your config file so we can confirm that its pointing to the correct file?

**Comment by sajidurehman** [comment]
Please see the attachment. 
[config.zip](https://github.com/ml-evs/matador/files/4688652/config.zip)

**Comment by ml-evs** [comment]
Sorry, I mean your personal config file e.g. `.matadorrc` or `matadorrc.yaml` if you're using the default one.

**Comment by sajidurehman** [comment]
Sorry for incovience. Please see the matadorrc.yaml
[matadorrc.zip](https://github.com/ml-evs/matador/files/4688702/matadorrc.zip)

Actually, i didn't fine the .matadorrc file. could you please let me know the the exact path ?

**Comment by ml-evs** [comment]
So `.matadorrc` is a file you can make yourself that contains your personal settings (you can put it in your home directory and it will be used as the default). It's also fine to just modify the default settings, which are read from the file that you just sent i.e. `matador/config/matadorrc.yml`.

When you run `dispersion <seed>`, it should print which config file it is using, could you paste that line here too?

The easiest thing to do is probably to make a file called `.matadorrc` in your home directory, and paste in the settings below:

```yaml
plotting:
  default_style: matador
  element_colours: ./my_vesta_elements.ini

run3:
  castep_executable: castep
  optados_executable: optados
```

where you should replace `./my_vesta_elements.ini` with the absolute path to the vesta file you want to use.
